name: Update Docusaurus Version
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'
      - run: npm ci
        working-directory: ./docs
      - run: npm run docusaurus docs:version ${{ github.event.release.tag_name }}
        working-directory: ./docs
      - name: Commit files
        run: |
          git config --local user.email "bstudios-bot@users.noreply.github.com"
          git config --local user.name "BStudios Bot"
          git commit -m "Update docs to ${{ github.event.release.tag_name }}" -a
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          branch: main